// RU navigation labels for research section — uncomment each key once its
// .mdx file has been generated by `pnpm translate`.
export default {
  // index: 'Обзор',
  // threads: 'Цепочки',
  // factsheets: 'Карточки фактов',
  // promoting: 'Продвижение в дерево',
} as Record<string, string>;
