import type { ProofStatementData, SourceEntry } from './proof-tab';

// ---------------------------------------------------------------------------
// Markdown export
// ---------------------------------------------------------------------------

export function exportProofAsMarkdown(
  data: ProofStatementData,
  personName: string,
  sources: Pick<SourceEntry, 'title' | 'type' | 'note'>[],
): string {
  const lines: string[] = [];

  lines.push(`# Proof Summary: ${personName}`);
  lines.push('');
  lines.push(`**Date:** ${data.conclusionDate}`);
  lines.push(`**Confidence:** ${capitalize(data.confidenceLevel)}`);
  lines.push('');

  lines.push('## Research Question');
  lines.push('');
  lines.push(data.question || '_No question specified._');
  lines.push('');

  lines.push('## Sources Consulted');
  lines.push('');
  if (sources.length === 0) {
    lines.push('_No sources selected._');
  } else {
    sources.forEach((s, i) => {
      const note = s.note ? ` -- ${s.note}` : '';
      lines.push(`${i + 1}. ${s.title} (${s.type})${note}`);
    });
  }
  lines.push('');

  lines.push('## Information Analysis');
  lines.push('');
  lines.push(data.analysis || '_No analysis provided._');
  lines.push('');

  lines.push('## Conclusion');
  lines.push('');
  lines.push(data.conclusion || '_No conclusion provided._');
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// PDF export
// ---------------------------------------------------------------------------

export async function exportProofAsPdf(
  data: ProofStatementData,
  personName: string,
  sources: Pick<SourceEntry, 'title' | 'type' | 'note'>[],
): Promise<void> {
  const { jsPDF } = await import('jspdf');

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const addPageIfNeeded = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = margin;
    }
  };

  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(`Proof Summary: ${personName}`, margin, y);
  y += 8;

  // Subtitle
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120, 120, 120);
  doc.text(
    `Date: ${data.conclusionDate}  |  Confidence: ${capitalize(data.confidenceLevel)}`,
    margin,
    y,
  );
  y += 6;

  // Horizontal rule
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;
  doc.setTextColor(0, 0, 0);

  // Section: Research Question
  y = addSection(doc, 'Research Question', data.question || 'No question specified.', margin, y, contentWidth);

  // Section: Sources Consulted
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  addPageIfNeeded(12);
  doc.text('Sources Consulted', margin, y);
  y += 7;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  if (sources.length === 0) {
    addPageIfNeeded(6);
    doc.text('No sources selected.', margin, y);
    y += 6;
  } else {
    for (let i = 0; i < sources.length; i++) {
      const s = sources[i];
      const note = s.note ? ` -- ${s.note}` : '';
      const text = `${i + 1}. ${s.title} (${s.type})${note}`;
      const lines = doc.splitTextToSize(text, contentWidth) as string[];
      addPageIfNeeded(lines.length * 5 + 2);
      doc.text(lines, margin, y);
      y += lines.length * 5 + 2;
    }
  }
  y += 4;

  // Section: Information Analysis
  y = addSection(doc, 'Information Analysis', data.analysis || 'No analysis provided.', margin, y, contentWidth);

  // Section: Conclusion
  y = addSection(doc, 'Conclusion', data.conclusion || 'No conclusion provided.', margin, y, contentWidth);

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 10;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by Ancstra -- ${data.conclusionDate}`, margin, footerY);

  // Download
  const filename = `${personName.replace(/\s+/g, '-')}-proof-summary-${data.conclusionDate}.pdf`;
  doc.save(filename);
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function addSection(
  doc: InstanceType<typeof import('jspdf').jsPDF>,
  title: string,
  body: string,
  margin: number,
  y: number,
  contentWidth: number,
): number {
  const pageHeight = doc.internal.pageSize.getHeight();

  const checkPage = (needed: number) => {
    if (y + needed > pageHeight - 20) {
      doc.addPage();
      y = margin;
    }
  };

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  checkPage(12);
  doc.text(title, margin, y);
  y += 7;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  const lines = doc.splitTextToSize(body, contentWidth) as string[];
  for (const line of lines) {
    checkPage(6);
    doc.text(line, margin, y);
    y += 5;
  }
  y += 6;

  return y;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
